// <auto-generated />
namespace planner09.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class planner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(planner));
        
        string IMigrationMetadata.Id
        {
            get { return "201902130116482_planner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
